version: '3'

services:
  proxy:
    image: nginx:latest
    ports:
      - 10011:80
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
    depends_on:
      - bot
      - app

  app:
    build: .
    networks:
      - internal

  bot:
    build: bot
    environment:
      APPNAME: Admin
      APPURL: http://app:8080/
      APPURLREGEX: ^http://app:8080/.*$
      APPFLAG: ARA5{7_15_mY_LuCKy_nUmb3r_h4HaH4ha}
      APPLIMIT: 2
      APPLIMITTIME: 60
    networks:
      - internal

networks:
  internal:
